Update README_template.md
Vampire/command-framework pull request #3
Opened 2022-03-03 04:01 UTC by WalkerKnapp

2022-03-03 14:51 UTC, Vampire requested changes
Thank you very much, I have some annotations and suggestions though. Mind quickly looking through them? :-)

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +If you want to have support for an additional framework, do not hesitate to open a pull request or feature request issue.
```suggestion
If you want to have support for an additional framework, do not hesitate to open a pull request or feature request
issue.
```

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +only the explicitly configured ones are used.
```suggestion
or `Cmd` suffix / prefix stripped and the first letter lowercased is used as a default. If at least one alias is
configured, only the explicitly configured ones are used.
```

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
>  the command handler can be told to execute the command asynchronously.
```suggestion
By overwriting the `Command#isAsynchronous()` method or applying the [`@Asynchronous`][@Asynchronous JavaDoc]
annotation, the command handler can be told to execute the command asynchronously.
```

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +To further customize the behavior of a command, you can either annotate the command class or overwrite the
```suggestion
To further customize the behavior of a command, you can either annotate the command class or overwrite the
```

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +for example, in a custom help command.
```suggestion
the description of the command can be configured. This description is not currently used by this framework, but it can
be used, for example, in a custom help command.
```

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +help command.
```suggestion
command can be configured. This usage can be used, for example, in a custom help command.
```
Whether it is used or not depends on whether the parameter parser is used or not.
I intentionally did not write here that it is not used opposed to the description which is really not used by the framework currently, as it **is** used under certain circumstances.

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +separately evaluated or used as documentation.
```suggestion
separately evaluated or used as documentation. The default implementations of those methods are the only locations
where the annotations are evaluated by default. Every other place calls the methods on the command implementation.
```
Imho the new text is too condensed.
What do you think about re-adding these two sentences to the end?
Probably cleaned from errors of course :-D

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +If at the end of the initialization phase, or any before/after sub phases, the command is set
```suggestion
If at the end of the initialization phase, or any before / after sub phases, the command is set
```

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +If at the end of the initialization phase, or any before/after sub phases before the
```suggestion
If at the end of the initialization phase, or any before / after sub phases before the
```

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +If at the end of the initialization phase, any before/after sub phases before the
```suggestion
If at the end of the initialization phase, or any before / after sub phases before the
```

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
> +method, you can transform current command context given a phase, or return a completely new command context.
```suggestion
method, given the current phase, you can transform the current command context, or even return a completely new one.
```

2022-03-03 14:51 UTC, Vampire commented on readme/README_template.md
>  a provider that returns the mention string for the bot as command prefix if Javacord is used as the underlying
```suggestion
a transformer that returns the mention string for the bot as command prefix if Javacord is used as the underlying
```

2022-03-03 17:09 UTC, WalkerKnapp commented on readme/README_template.md
> +separately evaluated or used as documentation.
Sure, here is a way you could reword it to flow a little bit better, let me know what you think

```suggestion
separately evaluated or used as documentation. For all functionality (i.e. command handlers),
command-framework uses the command method implementations. Annotations are only read
in the default implementations of those methods.
```

2022-03-03 17:12 UTC, WalkerKnapp commented on readme/README_template.md
> +help command.
Ah, I see. I just moved this phrasing from the `Command Description` section.

2022-03-03 17:23 UTC, Vampire commented on readme/README_template.md
> +separately evaluated or used as documentation.
i.e. is not correct, is it?
That would mean all functionality is in the command handlers only.
How about
```suggestion
separately evaluated or used as documentation. For all functionality this framework uses the command method
implementations. The annotations are only read in the default implementations of those methods.
```

2022-03-03 21:59 UTC, WalkerKnapp commented on readme/README_template.md
> +separately evaluated or used as documentation.
Oh, yes, it should be `i.g.` instead. But you're right that it is a bit unnecessary. That last version lgtm!

2022-03-04 10:46 UTC, closed without merging

2022-03-04 10:49 UTC, Vampire commented
Thank you very much, I picked it manually to the master branch. :-)